name: tiny_locator
description: Tiny service locator that provides a global access point to services.
version: 1.0.0+2
homepage: https://github.com/zuvola/tiny_locator

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
